### ISSUE TITLE
Cannot download data models when working under proxy

### ISSUE THREAD

**Issue by son-phamngoc** [FIWARE/tutorials.Understanding-At-Context#12]
Hello,
I'm trying to execute this tutorial and got the following error:
```
./services validate ./baseline.yaml
Onoes! The API is invalid. Error downloading https://fiware.github.io/tutorials.NGSI-LD/models/openstreetmap.yaml 
getaddrinfo ENOTFOUND fiware.github.io
```
```
./services ngsi ./baseline.yaml
Creating a NGSI-LD @context file for normalized interactions
Cannot dereference file. The file is invalid. Error downloading https://fiware.github.io/tutorials.NGSI-LD/models/building.yaml 
getaddrinfo ENOTFOUND fiware.github.io
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'components' of undefined
    at Object.getContext (/usr/src/app/bin/jsonld.js:73:19)
    at Object.ngsi (/usr/src/app/bin/swagger.js:49:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
datamodels.context-ngsi.jsonld created
```

I'm working under proxy of my company, so possibly, proxy causes this error.
I can access the links successfully on browser.
Is there any way to configure proxy to solve this problem?
Thank you for your support.

**Comment by fbuedding** [comment]
I'm facing the same issue, without a proxy. OS: Linux Arch

**Comment by jmormal** [comment]
I am having the same issue. I also get it in gitpod and on my own network. 

It is not exactly the same, I get 

```
Onoes! The API is invalid. Error downloading https://fiware.github.io/tutorials.NGSI-LD/models/building.yaml 
AbortController is not defined.
```
Thanks for your support.

**Comment by jason-fox** [comment]
Looks like the Node version is no longer supported. Pull the latest changes and recreate your docker image.

```console
git pull
./services create 
```

**Comment by jmormal** [comment]
Thanks! Now it works
